export const API_ERROR_CODES = {
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DATASET_NOT_FOUND: "DATASET_NOT_FOUND",
  EXPORT_TOO_LARGE: "EXPORT_TOO_LARGE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  IMPORT_FAILED: "IMPORT_FAILED",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
